"""AddTask use case - create a new todo task."""

from datetime import datetime

from src.application.dto.task_dto import TaskDTO
from src.application.dto.task_input_dto import TaskInputDTO
from src.domain.entities.task import Task
from src.domain.repositories.task_repository import TaskRepository


class AddTaskUseCase:
    """
    Use case for adding a new task.

    This implements the application logic for creating tasks,
    coordinating between the interface and domain layers.

    Responsibilities:
        - Accept TaskInputDTO from interface layer
        - Create Task entity with auto-generated ID
        - Persist Task via repository
        - Return TaskDTO to interface layer

    Business Rules:
        - Title and description are validated by Task entity
        - ID is auto-generated by repository
        - is_complete defaults to False
        - created_at is set to current timestamp
    """

    def __init__(self, repository: TaskRepository):
        """
        Initialize use case with repository dependency.

        Args:
            repository: TaskRepository implementation for persistence
        """
        self._repository = repository

    def execute(self, input_dto: TaskInputDTO) -> TaskDTO:
        """
        Execute the add task use case.

        Args:
            input_dto: TaskInputDTO containing title and description

        Returns:
            TaskDTO with the created task data including auto-generated ID

        Raises:
            ValidationError: If title or description violate validation rules
        """
        # Create Task entity (validation happens in __post_init__)
        task = Task(
            id=0,  # ID will be auto-generated by repository
            title=input_dto.title,
            description=input_dto.description,
            is_complete=False,
            created_at=datetime.now(),
        )

        # Persist via repository (ID auto-generated here)
        saved_task = self._repository.add(task)

        # Convert to DTO for interface layer
        return TaskDTO(
            id=saved_task.id,
            title=saved_task.title,
            description=saved_task.description,
            is_complete=saved_task.is_complete,
            created_at=saved_task.created_at,
        )
